### ISSUE TITLE
Write a blog post on confidential data

### ISSUE THREAD

**Issue by k-doering-NOAA** [noaa-fisheries-integrated-toolbox/FIT-committee#39]
Write one resources blog post that provides technical guidance on how to work with confidential data in open science workflows (e.g., R toolchains).

**Comment by k-doering-NOAA** [comment]
@mollystevens-noaa, since you also work with confidential data a lot, would you mind also taking a look at this confidential data post (see https://github.com/noaa-fisheries-integrated-toolbox/resources/blob/add-conf-dat-post/_posts/2023-11-20-confidential-data.md) and editing directly or submitting a pr to the branch?

If there are major issues with it, let me know, and we can schedule time to chat

**Comment by k-doering-NOAA** [comment]
Additional changes to add to the post (for Kathryn to do)
- add authors of post 
- add link to google drive with additional sensitive fisheries data guidance
- use "sensitive information" instead of confidential data throughout the post.

**Comment by mollystevens-noaa** [comment]
@k-doering-NOAA @erinsteiner-NOAA please check my (mostly minor) edits for accuracy; is there a link we could add to the MSA section?

[Sensitive information and confidential data blog post](https://github.com/noaa-fisheries-integrated-toolbox/resources/blob/add-conf-dat-post/_posts/2023-11-20-confidential-data.md)

Is the text chunk....

> And the exceptions for information collected by observers are: (A) as authorized by a fishery management plan or regulations under the authority of the North Pacific Council to allow disclosure to the public of weekly summary bycatch information identified by vessel or for haul-specific bycatch information without vessel identification;

...specific to the North Pacific Council?  I didn't want to edit bits that seemed like copied legalese, but thought this could maybe be made more generic if possible/applicable to other regions.

P.S. Sorry if yall got double-emailed, I realized the issue here seemed more appropriate for this follow-up as opposed to the one on the [resources page](https://github.com/noaa-fisheries-integrated-toolbox/resources/issues/56)

**Comment by k-doering-NOAA** [comment]
Thanks @mollystevens-noaa !

I think @erinsteiner-noaa will have help with the text chunk generalization question

For links to MSA, here are two options, I'm not sure if it is better to have the plain language explainer and video or the link to the document.
- https://www.fisheries.noaa.gov/topic/laws-policies/magnuson-stevens-act
- https://www.fisheries.noaa.gov/resource/document/magnuson-stevens-fishery-conservation-and-management-act

**Comment by erinsteiner-NOAA** [comment]
@mollystevens-noaa unfortunately it copied straight out of [MSA](https://media.fisheries.noaa.gov/dam-migration/msa-amended-2007.pdf), it would have been nice if they had included us all!

**Comment by k-doering-NOAA** [comment]
The [blog post is live](https://noaa-fisheries-integrated-toolbox.github.io/resources/noaa%20resources/confidential-data/)
